from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_multichannel_exr_render(object):
    def setupUi(self, multichannel_exr_render):
        multichannel_exr_render.setObjectName(_fromUtf8("multichannel_exr_render"))
        multichannel_exr_render.resize(948, 368)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        multichannel_exr_render.setFont(font)
        self.centralwidget = QtGui.QWidget(multichannel_exr_render)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.exr_path_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exr_path_lineEdit.sizePolicy().hasHeightForWidth())
        self.exr_path_lineEdit.setSizePolicy(sizePolicy)
        self.exr_path_lineEdit.setInputMask(_fromUtf8(""))
        self.exr_path_lineEdit.setText(_fromUtf8(""))
        self.exr_path_lineEdit.setObjectName(_fromUtf8("exr_path_lineEdit"))
        self.horizontalLayout.addWidget(self.exr_path_lineEdit)
        self.browse_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_pushButton.sizePolicy().hasHeightForWidth())
        self.browse_pushButton.setSizePolicy(sizePolicy)
        self.browse_pushButton.setObjectName(_fromUtf8("browse_pushButton"))
        self.horizontalLayout.addWidget(self.browse_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.exr_path_listWidget = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.exr_path_listWidget.sizePolicy().hasHeightForWidth())
        self.exr_path_listWidget.setSizePolicy(sizePolicy)
        self.exr_path_listWidget.setDragDropOverwriteMode(False)
        self.exr_path_listWidget.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.exr_path_listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.exr_path_listWidget.setObjectName(_fromUtf8("exr_path_listWidget"))
        self.verticalLayout_4.addWidget(self.exr_path_listWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.load_pushButton = QtGui.QPushButton(self.centralwidget)
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        self.horizontalLayout_5.addWidget(self.load_pushButton)
        self.export_pushButton = QtGui.QPushButton(self.centralwidget)
        self.export_pushButton.setObjectName(_fromUtf8("export_pushButton"))
        self.horizontalLayout_5.addWidget(self.export_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.channel_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_lineEdit.sizePolicy().hasHeightForWidth())
        self.channel_lineEdit.setSizePolicy(sizePolicy)
        self.channel_lineEdit.setObjectName(_fromUtf8("channel_lineEdit"))
        self.horizontalLayout_6.addWidget(self.channel_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.firstframe_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstframe_lineEdit.sizePolicy().hasHeightForWidth())
        self.firstframe_lineEdit.setSizePolicy(sizePolicy)
        self.firstframe_lineEdit.setInputMask(_fromUtf8(""))
        self.firstframe_lineEdit.setObjectName(_fromUtf8("firstframe_lineEdit"))
        self.horizontalLayout_4.addWidget(self.firstframe_lineEdit)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.lastframe_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastframe_lineEdit.sizePolicy().hasHeightForWidth())
        self.lastframe_lineEdit.setSizePolicy(sizePolicy)
        self.lastframe_lineEdit.setObjectName(_fromUtf8("lastframe_lineEdit"))
        self.horizontalLayout_4.addWidget(self.lastframe_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.add_path_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_path_pushButton.sizePolicy().hasHeightForWidth())
        self.add_path_pushButton.setSizePolicy(sizePolicy)
        self.add_path_pushButton.setObjectName(_fromUtf8("add_path_pushButton"))
        self.horizontalLayout_7.addWidget(self.add_path_pushButton)
        self.remove_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_pushButton.sizePolicy().hasHeightForWidth())
        self.remove_pushButton.setSizePolicy(sizePolicy)
        self.remove_pushButton.setObjectName(_fromUtf8("remove_pushButton"))
        self.horizontalLayout_7.addWidget(self.remove_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.reset_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_pushButton.setSizePolicy(sizePolicy)
        self.reset_pushButton.setObjectName(_fromUtf8("reset_pushButton"))
        self.horizontalLayout_8.addWidget(self.reset_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.cancel_pushButton.setSizePolicy(sizePolicy)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout_8.addWidget(self.cancel_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.write_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_lineEdit.sizePolicy().hasHeightForWidth())
        self.write_lineEdit.setSizePolicy(sizePolicy)
        self.write_lineEdit.setInputMask(_fromUtf8(""))
        self.write_lineEdit.setObjectName(_fromUtf8("write_lineEdit"))
        self.horizontalLayout_9.addWidget(self.write_lineEdit)
        self.renderpath_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderpath_pushButton.sizePolicy().hasHeightForWidth())
        self.renderpath_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.renderpath_pushButton.setFont(font)
        self.renderpath_pushButton.setObjectName(_fromUtf8("renderpath_pushButton"))
        self.horizontalLayout_9.addWidget(self.renderpath_pushButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.local_radioButton = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_radioButton.sizePolicy().hasHeightForWidth())
        self.local_radioButton.setSizePolicy(sizePolicy)
        self.local_radioButton.setObjectName(_fromUtf8("local_radioButton"))
        self.verticalLayout_3.addWidget(self.local_radioButton)
        self.farm_radioButton = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farm_radioButton.sizePolicy().hasHeightForWidth())
        self.farm_radioButton.setSizePolicy(sizePolicy)
        self.farm_radioButton.setObjectName(_fromUtf8("farm_radioButton"))
        self.verticalLayout_3.addWidget(self.farm_radioButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.submit_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_pushButton.sizePolicy().hasHeightForWidth())
        self.submit_pushButton.setSizePolicy(sizePolicy)
        self.submit_pushButton.setObjectName(_fromUtf8("submit_pushButton"))
        self.horizontalLayout_3.addWidget(self.submit_pushButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        multichannel_exr_render.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(multichannel_exr_render)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        multichannel_exr_render.setStatusBar(self.statusbar)

        self.retranslateUi(multichannel_exr_render)
        QtCore.QMetaObject.connectSlotsByName(multichannel_exr_render)


def retranslateUi(self, multichannel_exr_render):
    multichannel_exr_render.setWindowTitle(_translate("multichannel_exr_render", "Multichannel EXR Converter", None))
    self.browse_pushButton.setText(_translate("multichannel_exr_render", "Browse", None))
    self.load_pushButton.setText(_translate("multichannel_exr_render", "Load", None))
    self.export_pushButton.setText(_translate("multichannel_exr_render", "Export", None))
    self.label_2.setText(_translate("multichannel_exr_render", "Channel Name", None))
    self.label.setText(_translate("multichannel_exr_render", "-", None))
    self.add_path_pushButton.setText(_translate("multichannel_exr_render", "Add", None))
    self.remove_pushButton.setText(_translate("multichannel_exr_render", "Remove", None))
    self.reset_pushButton.setText(_translate("multichannel_exr_render", "Reset", None))
    self.cancel_pushButton.setText(_translate("multichannel_exr_render", "Cancel", None))
    self.renderpath_pushButton.setText(_translate("multichannel_exr_render", "Save", None))
    self.local_radioButton.setText(_translate("multichannel_exr_render", "Local", None))
    self.farm_radioButton.setText(_translate("multichannel_exr_render", "Farm", None))
    self.submit_pushButton.setText(_translate("multichannel_exr_render", "Submit", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    multichannel_exr_render = QtGui.QMainWindow()
    ui = Ui_multichannel_exr_render()
    ui.setupUi(multichannel_exr_render)
    multichannel_exr_render.show()
    sys.exit(app.exec_()